### ISSUE TITLE
libcaffe Compilation error

### ISSUE THREAD

**Issue by kordokrip** [seokhoonboo/caffe-boo#1]
Installation Environment

Windows 7 64 bit
CUDA 8.0
cuDNN v5
Visual studio 15
Anaconda Python 2.7

The following message error occurs. I can not figure out where to fix it and I'm looking for help.

The path specified for SourceFile at 'C:\caffe-master\src\caffe\layers\upsample_layer.cu' does not exist.	libcaffe	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\CUDA 8.0.targets	411

**Comment by seokhoonboo** [comment]
you just remove 'upsample_layer.cu' in project
