### ISSUE TITLE
__max/__min in batch_renorm_layer.cu in Ubuntu

### ISSUE THREAD

**Issue by John1231983** [seokhoonboo/caffe-boo#2]
I am using CAFFE in Ubuntu. I want to use your implementation of batch_renorm_layer. I merged but I got the error of __max/__min function in the line. 
```
Dtype cur_r_max = __max(1, __min(1 + (step - step_to_init_ + 1)*(r_max_ - 1) / (step_to_r_max_ - step_to_init_), r_max_));
			Dtype cur_r_min = 1. / cur_r_max;
			Dtype cur_d_max = __max(0, __min((step - step_to_init_ + 1)*d_max_ / (step_to_d_max_ - step_to_init_), d_max_));
			Dtype cur_d_min = -cur_d_max;
```

src/caffe/layers/batch_renorm_layer.cu(115): error: identifier "__min" is undefined

How to use these function in Ubuntu? I tried std::max and std::min but it failed. Thanks

**Comment by strawberryfg** [comment]
How did you solve that? @John1231983  Thanks!
